BUILD_PATH = build/

PORT ?= $(shell sed -n 's/^default_port: \(.*\)/\1/p' ./sketch.yaml | tail -n 1)
BAUD ?= $(shell sed -n 's/ *baudrate: \([0-9]*\)/\1/p' ./sketch.yaml | tail -n 1)

EXTRA_FLAGS = -DBAUD=$(BAUD)

$(BUILD_PATH): . project.h
	arduino-cli compile --build-path $(BUILD_PATH) -j 0 \
		--build-property compiler.cpp.extra_flags=$(EXTRA_FLAGS) \
		--build-property compiler.c.extra_flags=$(EXTRA_FLAGS)

project.h: sketch.yaml
	# I'd rather not make this file, but you'll want it if you like the idea of your lsp working
	@echo "Creating project.h"
	@echo "// THIS FILE IS AUTOGENERATED. DO NOT TOUCH!" > project.h
	@echo "#define BAUD $(BAUD)" >> project.h

.PHONY: upload
upload: $(BUILD_PATH)
	arduino-cli upload --build-path $(BUILD_PATH)

.PHONY: info
info:
	@echo 'Port: $(PORT)'
	@echo 'Baud: $(BAUD)'
	@echo 'Build Path: $(BUILD_PATH)'

.PHONY: clean
clean:
	rm -rf build/

.PHONY: monitor
monitor:
	arduino-cli monitor

# alternative to arduino-cli monitor
.PHONY: pico
pico:
	picocom $(PORT) -b $(BAUD) --imap crcrlf,lfcrlf --send-cmd 'ascii-xfr -svn' --receive-cmd 'ascii-xfr -rvn'
